### ISSUE TITLE
the board doesn't show up in bootloader mode

### ISSUE THREAD

**Issue by cpu0x00** [adafruit/Adafruit-Proximity-Trinkey-PCB#2]
Hello, its my first time using trinkies and im having a problem with the proximity trinkey when i plug it in, normally it activates the light sensors but when i try to plug it in pressing the bootloader button it just don't show up on my computer so if someone can provide a little help about how can i get to the bootloader mode that will be great 

my machine is linux but tried it on windows vm too still doesn't show up

**Comment by ladyada** [comment]
hiya, questions about how to use adafruit products are best posted in the adafruit forums  at [forums.adafruit.com](forums.adafruit.com/)
thats where tech support is handled - github issues are where folks can issue bug reports (e.g. something that ought to work but doesnt due to a hardware or software bug)

thanks! :)
